### ISSUE TITLE
Question: what about socket.io?

### ISSUE THREAD

**Issue by romelperez** [now-examples/ws-servers#1]
[socket.io](http://socket.io/) has been and is currently one great option to create web sockets with [Node.js](http://nodejs.org).

Would there be examples using it?

**Comment by TooTallNate** [comment]
socket.io is an excellent abstraction _on top of_ regular WebSockets. In fact, [socket.io uses the `uws` module internally](https://github.com/socketio/engine.io/commit/91dd49d1c24a532de3587eb1ef74f960e6e9072e), which we are including in the benchmarks here.

Feel free to [join our Slack group](https://zeit.chat) if you would like any further assistance deploying a socket.io server to Now.
